export { default as Certification, type ICertification } from './Certification'
export { default as Client, type IClient } from './Client'
export { default as Clinic, type IClinic } from './Clinic'
export { default as Comment, type IComment } from './Comment'
export { default as Degree, type IDegree } from './Degree'
export { default as File, type IFile } from './File'
export { default as Like, type ILike } from './Like'
export { default as Medic, type IMedic } from './Medic'
export { default as Procedure, type IProcedure } from './Procedure'
export { default as Product, type IProduct } from './Product';
export { default as Qualification, type IQualification } from './Qualification'
export { default as Quote, type IQuote } from './Quote';
export { default as User, type AUser } from './User';
